---
title: 'Python'
title_note: 'üêç Python'
date: '19/06/22'
update: '19/06/22'
excerpt: 'Anota√ß√µes gerais sobre o Python.'
cover_image: '/images/python-icon.png'
---


- **[Documenta√ß√£o oficial (por vers√£o)](https://www.python.org/doc/versions/)**
- **[Padr√µes de design e estilo em python](https://www.monolitonimbus.com.br/padroes-de-design-e-estilo-em-python/)**
- **[Padr√µes de Projeto em Python](https://github.com/kelvins/design-patterns-python)**
- **[10 dicas/falhas que programadores em Python cometem (EN)](https://www.toptal.com/python/top-10-mistakes-that-python-programmers-make)**

## Cria√ß√£o de classes e objetos

Cria√ß√£o da classe *Pessoa*, com os atributos *nome* e *idade*:

```py
class Pessoa:
    def __init__(self, nome, sobrenome, idade):
        self.nome = nome
        self.sobrenome = sobrenome
        self.idade = idade

    def escrever_nome(self):
        print(self.nome, self.sobrenome)

    primeira_pessoa = Pessoa('Vinicius', 'Pessanha', '24')
    primeira_pessoa.escrever_nome()
    print (primeira_pessoa.idade) # ir√° printar '24'
```

Todas as classes, por padr√£o, possuem a fun√ß√£o `__init__()`. Esta fun√ß√£o √© chamada automaticamente sempre que uma classe √© usada para criar um novo objeto.

O par√¢metro `self` √© usado para acessar vari√°veis que pertencem √† classe.

## Heran√ßa

[Refer√™ncia](https://www.w3schools.com/python/python_inheritance.asp)

Cria√ß√£o da classe *Estudante*, que herda a classe *Pessoa* mencionada no exemplo anterior:

```py
class Estudante(Pessoa):
    pass

primeiro_estudante = Estudante('Vinicius', 'Pessanha', '24')
primeiro_estudante.escrever_nome()
```

Ao criar uma classe que precise herdar a funcionalidade de outra classe, devemos mencionar a classe Pai entre par√™nteses durante a cria√ß√£o da nova classe. No exemplo acima, a classe *Estudante* tamb√©m poder√° utilizar o m√©todo `escrever_nome()`.

Em alguns casos, al√©m de herdar os atributos e m√©todos de uma classe, pode haver a necessidade de criar novos atributos. Desse modo, devemos fazer uma refer√™ncia ao `__init__()` da classe que est√° sendo herdada. Caso essa refer√™ncia n√£o seja feita e um novo `__init__()` seja criado, este novo  `__init__()` ir√° sobrepor o `__init__()` herdado. Veja o exemplo abaixo:

```py
class Estudante(Pessoa):
    def __init__(self, nome, sobrenome, idade): # Fun√ß√£o da classe Estudante
        Pessoa.__init__(self, nome, sobrenome, idade) # Fun√ß√£o da classe Pessoa
```

Caso seja necess√°rio herdar n√£o s√≥ as funcionalidades/m√©todos, mas tamb√©m os atributos da classe, dever√° ser usada a fun√ß√£o `super()`, conforme o exemplo abaixo:

```py
class Estudante(Pessoa):
    def __init__(self, nome, sobrenome, idade):
        super().__init__(self, nome, sobrenome, idade)
```

Usando o mesmo exemplo acima, podemos adicionar novas propriedades e m√©todos da seguinte forma:

```py
class Estudante(Pessoa):
    def __init__(self, nome, sobrenome, idade, ano_formatura):
        super().__init__(self, nome, sobrenome, idade)
        self.ano_formatura = ano_formatura

    def boas_vindas(self):
        print(f"Bem-vindo {self.nome} {self.sobrenome}, formando de {ano_formatura}.")
```

## Tratamento de erros com try-except

Algumas instru√ß√µes podem ser encontradas [neste link](https://www.w3schools.com/python/python_try_except.asp).

- Tratar apenas um erro

    ```py
    try:
        var1 = class.name
    except Exception as error:
        print(f'Erro ocorrido: {error}')
    ```

- Tratar mais de um tipo de erro na mesma exce√ß√£o

    ```py
    try:
        var1 = class.name
    except (ValueError, IndexError) as error:
        print(f'Erro ocorrido: {error}')
    ```

- Para conseguir uma mensagem de erro mais detalhada (como mostrado nas IDEs), deve-se utilizar a biblioteca nativa `traceback`:

    ```py
    import traceback

    try:
        var2 = int(class.name)
    except (Exception,):
        print(f'Erro apresentado: \n{traceback.format_exc()}')
    ```

- Para interromper a execu√ß√£o de um c√≥digo caso determinado erro ocorra, dever√° se usar a palavra `raise`:

    ```py
        try:
            var2 = int(class.name)
            if var2 is None:
                raise Exception(f'Erro apresentado: \n{traceback.format_exc()}')
    ```
